# Generated by Django 4.1.5 on 2023-01-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default=2, upload_to='gallary'),
            preserve_default=False,
        ),
    ]
